### ISSUE TITLE
Add a ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by felipemfp** [GeoGuideProject/backend#5]
### Briefing

GitHub offers a way to create `ISSUE_TEMPLATE.md` that could be used for standardization.

We could have one like:

```md
### Briefing
Brief description of this issue or feature.

### Tasks

- [ ] Task 1
- [ ] Task 2
```

### Tasks

- [x] [Create](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/) the ISSUE_TEMPLATE.md above

**Comment by 142ayushkumar** [comment]
Can you assign me this issue?

**Comment by felipemfp** [comment]
Sorry, @142ayushkumar! Looks like @jvaesteves already did it.
